name: "Deploy to Cloudflare Pages"

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    name: "Build mdBook on GitHub and Deploy on Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Setup mdBook"
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - run: mdbook build

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('book/') }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "c5541e8801de162b20b23687ef90296e"
          projectName: "speedboat-docs"
          directory: "./book"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
